tap "bigcoke233/tap", "https://github.com/BigCoke233/homebrew-tap.git"
tap "bigwig-club/brew"
tap "homebrew/services"
tap "j178/tap"
tap "krishkrosh/apps"
tap "laishulu/homebrew"
tap "lihaoyun6/tap"
tap "pakerwreah/calendr"
tap "spring-io/tap"
tap "tw93/tap"
brew "facad"
brew "fd"
brew "ffmpeg"
brew "forgejo-cli"
brew "gh"
brew "git"
brew "gnupg"
brew "hugo"
brew "lazygit"
brew "mas"
brew "mihomo"
brew "mise"
brew "neofetch"
brew "neovim"
brew "ripgrep"
brew "opencode"
brew "pandoc"
brew "pinentry-mac"
brew "plantuml"
brew "tree-sitter-cli"
brew "wget"
brew "witr"
brew "xdg-ninja", args: ["HEAD"]
brew "yazi"
brew "you-get"
brew "zip"
brew "bigcoke233/tap/wthis"
brew "laishulu/homebrew/macism"
brew "tw93/tap/mole"
cask "betterdisplay"
cask "calendr"
cask "chatgpt"
cask "ghostty"
cask "hammerspoon"
cask "helium-browser"
cask "hiddenbar"
cask "keka"
cask "lulu"
cask "netnewswire"
cask "onlyoffice"
cask "qq"
cask "raycast"
cask "wechat"
mas "1Capture", id: 6742318274
mas "Dropover", id: 1355679052
mas "Googly Eyes", id: 6743048714
